/* Generated by PyToC Translator */

/* Boolean handling support */
#ifndef bool
#define bool int
#endif
#ifndef True
#define True (1)
#define False (0)
#endif


float global_array[3];

global_array = [1.1, 2.1, 3.5];

void in_func() {
    /* Local Variable Declarations */
    int a[3];

    /* Main Code */
    a = [4, 5, 6];
    print(a);
    print(a[0]);
}


