/* Generated by PyToC Translator */

/* Boolean handling support */
#ifndef bool
#define bool int
#endif
#ifndef True
#define True (1)
#define False (0)
#endif


int also;
int another;
int other;
int var;

var = 1;
other = -1;
another = -var;
also = (-var * -other);
