/* Generated by PyToC Translator */

/* Boolean handling support */
#ifndef bool
#define bool int
#endif
#ifndef True
#define True (1)
#define False (0)
#endif


int a[2];
int b[1];

a = [1, 2];
b = tuple(3);
print(a);
