/* Generated by PyToC Translator */

/* Boolean handling support */
#ifndef bool
#define bool int
#endif
#ifndef True
#define True (1)
#define False (0)
#endif


int g_var1;
int g_var2;

g_var1 = 4;
g_var2 = 5;

void test() {
    /* Local Variable Declarations */
    int g_var2;

    /* Main Code */
    print(g_var1);
    print(g_var2);
    g_var1 = 3;
    g_var2 = 2;
}


